spring:
  ai:
    mcp:
      client:
        name: mcp-client-dynamic-tool-update
        version: 1.0.0
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: http://localhost:8080